name: Build Matlab interface and upload to release
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_test_release:
    name: Build, test and release Matlab interface

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2019 ]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac
          - os: windows-2019
            platform: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Eigen
        working-directory: build_external
        run: bash  ../ci/install_eigen.sh

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Build and package interface
        uses: matlab-actions/run-command@v1
        with:
          command: cd interfaces/matlab, make_piqp

      - name: Run tests  in MATLAB
        uses: matlab-actions/run-command@v1
        with:
          command: cd interfaces/matlab, runtest_piqp

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./interfaces/matlab/piqp-matlab-${{ matrix.platform}}64.tar.gz

      - name: Upload tarballs
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./interfaces/matlab/piqp-matlab-${{ matrix.platform}}64.tar.gz
          asset_name: piqp-matlab-${{ matrix.platform}}64.tar.gz
          asset_content_type: application/gzip
